#!/bin/sh

# PHPStan check
./vendor/bin/phpstan analyse app/ routes/ tests/ database/factories database/seeders || exit 1

# Laravel Pint check
./vendor/bin/pint --test || exit 1

# PHP CodeSniffer check
./vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/ database/factories database/seeders || exit 1

# PHPUnit tests check
php artisan test || exit 1

echo "All checks passed, proceeding with commit."
exit 0
