services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - db
            - db_testing

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    db_testing:
        image: mysql:8.0
        container_name: laravel_db_testing
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_testing
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - db_testing_data:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - db
        networks:
            - laravel_network

volumes:
    db_data:
    db_testing_data:

networks:
    laravel_network:
        driver: bridge
